# Generated by Django 4.0.1 on 2022-02-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_status',
            field=models.CharField(blank=True, default='Not Sent', max_length=10, null=True),
        ),
    ]
