# Generated by Django 4.0.1 on 2022-02-04 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_delivery_date_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 7, 18, 6, 22, 16827), null=True),
        ),
    ]
