# Generated by Django 4.0.1 on 2022-02-04 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_order_comments_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 7, 18, 28, 2, 765703), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
