# Generated by Django 4.0.1 on 2022-02-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_gluten_free_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gluten_free_option',
        ),
    ]
