# Generated by Django 4.0.1 on 2022-02-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_gluten_free_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_cakes',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
